service: ses
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  region: eu-central-1

functions:
  mail:
    handler: handler.mail
    events:
      - httpApi:
          path: /send
          method: post
